# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Fri, 26 May 2023 16:20:54 +0000
*               @ALL          1
*               @user         8
