<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: admin
 * Date: Sat, 27 May 2023 17:24:33 +0000
 */

$conf['title'] = 'LEMARR';
$conf['license'] = 'cc-by-sa';
$conf['breadcrumbs'] = 0;
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
