<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: admin
 * Date: Sun, 28 May 2023 22:38:44 +0000
 */

$conf['title'] = 'LEMARR';
$conf['license'] = 'cc-by-sa';
$conf['breadcrumbs'] = 0;
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['target']['extern'] = '_blank';
