<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: admin
 * Date: Wed, 07 Jun 2023 18:03:07 +0000
 */

$conf['title'] = 'LERR';
$conf['license'] = 'cc-by-sa';
$conf['breadcrumbs'] = 0;
$conf['toptoclevel'] = '2';
$conf['useheading'] = '1';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['target']['extern'] = '_blank';
$conf['plugin']['commentsyntax']['toolbar_button'] = 1;
$conf['plugin']['commentsyntax']['use_cstyle_nest'] = 1;
$conf['plugin']['commentsyntax']['use_oneline_style'] = 1;
