# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Fri, 26 May 2023 16:20:54 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

admin:$2y$10$dnc9SQGCPudOTeSDS9zml.DGdoSXe.KU9832pJI4ZTpDkmCWYy1j2:Eric Sheffield:sheffie@miamioh.edu:admin,user
